# football prediction system with machine learning

In [87]:
import nltk
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab') 
nltk.download('stopwords')
nltk.download('omw-1.4')
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from ast import literal_eval

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [88]:
data = pd.read_csv("all_matches.csv")
data.head()

,date,home_team,away_team,home_score,away_score,tournament,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Scotland,False

In [89]:
data["homecountries"] = data.home_team
print(data.homecountries.unique())

['Scotland' 'England' 'Wales' 'Ireland' 'Uruguay' 'Austria' 'Hungary'
 'Argentina' 'Belgium' 'France' 'Netherlands' 'British Guiana' 'Bohemia'
 'Switzerland' 'Germany' 'Sweden' 'Denmark' 'Italy' 'South Africa' 'Chile'
 'Norway' 'Finland' 'Luxembourg' 'Russia' 'Philippines' 'China' 'Suriname'
 'Brazil' 'Japan' 'Paraguay' 'Spain' 'Czechoslovakia' 'Egypt'
 'Northern Ireland' 'Estonia' 'Costa Rica' 'Guatemala' 'Poland'
 'Yugoslavia' 'New Zealand' 'Romania' 'Latvia' 'Portugal' 'Australia'
 'Lithuania' 'Trinidad and Tobago' 'Turkey' 'Mexico' 'Aruba'
 'United States' 'Soviet Union' 'Haiti' 'Bulgaria' 'Canada' 'Jamaica'
 'Kenya' 'Azerbaijan' 'Georgia' 'Peru' 'Honduras' 'British Honduras'
 'Dutch East Indies' 'El Salvador' 'Uganda' 'Barbados' 'Greece' 'Cuba'
 'Curaçao' 'Faroe Islands' 'Mauritius' 'Dominica' 'Reunion'
 'New Caledonia' 'Palestine' 'Grenada' 'Guadeloupe' 'French Guiana'
 'Martinique' 'St Vincent & Grenadines' 'Panama' 'Colombia' 'Venezuela'
 'Bolivia' 'Saint Kitts and Nevis' 'Ecuador' 'Slovakia'
 'Bohemia and Moravia' 'Croatia' 'Iran' 'Afghanistan' 'Korea' 'Lebanon'
 'Syria' 'Nicaragua' 'Iceland' 'Albania' 'Southern Rhodesia' 'Hong Kong'
 'Tanganyika' 'French Somaliland' 'Northern Rhodesia' 'Madagascar'
 'South Vietnam' 'Macao' 'Singapore' 'India' 'South Korea' 'Thailand'
 'Belgian Congo' 'Ethiopia' 'Puerto Rico' 'Israel' 'Sierra Leone'
 'Zanzibar' 'Antigua and Barbuda' 'Saint Kitts' 'Netherlands Antilles'
 'Gold Coast' 'West Germany' 'Indonesia' 'East Germany' 'Fiji' 'Nigeria'
 'Montserrat' 'Ceylon' 'Pakistan' 'Tahiti' 'Saar' 'Gambia'
 'Portuguese Guinea' 'Jordan' 'Libya' 'New Hebrides' 'Burma' 'Taiwan'
 'French Togoland' 'Ivory Coast' 'French Congo' 'Cameroon' 'Malaya'
 'Cambodia' 'Sudan' 'North Korea' 'Ubangi-Shari' 'Malta' 'Tunisia' 'Iraq'
 'Morocco' 'Saudi Arabia' 'Ghana' 'Nyasaland' 'Algeria'
 'United Arab Republic' 'Dahomey' 'North Vietnam' 'Togo' 'Congo'
 'Mali Federation' 'Upper Volta' 'Cyprus' 'Saint Lucia' 'Kuwait' 'Senegal'
 'Liberia' 'Central African Republic' 'Chad' 'Guinea' 'Mali' 'Gabon'
 'Northern Cyprus' 'Congo-Leopoldville' 'Solomon Islands' 'Malaysia'
 'Niger' 'DR Congo' 'Bermuda' 'Tanzania' 'Zambia' 'Bahrain' 'Malawi'
 'Papua New Guinea' 'Dominican Republic' 'Guyana' 'Mauritania' 'Rhodesia'
 'Swaziland' 'Laos' 'Qatar' 'Bonaire' 'Khmer Republic' 'Lesotho' 'Bahamas'
 'South Yemen' 'Somalia' 'Zaire' 'United Arab Emirates' 'Sri Lanka'
 'Nepal' 'Bangladesh' 'Burundi' 'Guinea-Bissau' 'Mozambique' 'Guam'
 'Angola' 'Oman' 'São Tomé and Príncipe' 'Botswana' 'Benin' 'Cape Verde'
 'Seychelles' 'Rwanda' 'Comoros' 'Tuvalu' 'Wallis and Futuna' 'Tonga'
 'Kiribati' 'Brunei' 'Zimbabwe' 'Liechtenstein' 'Vanuatu' 'Greenland'
 'Western Samoa' 'Eastern Samoa' 'Belize' 'Djibouti' 'Maldives'
 'Burkina Faso' 'North Yemen' 'Anguilla' 'Equatorial Guinea'
 'Cayman Islands' 'Sint Maarten' 'Namibia' 'Saint Martin'
 'British Virgin Islands' 'San Marino' 'Slovenia' 'Moldova'
 'Comm of Indep States' 'Ukraine' 'Kazakhstan' 'Tajikistan' 'Uzbekistan'
 'Eritrea' 'Turkmenistan' 'Kyrgyzstan' 'Armenia' 'Belarus' 'Vietnam'
 'Yemen' 'Myanmar' 'Macedonia' 'Czechia' 'Gibraltar' 'Cook Islands'
 'Bosnia and Herzegovina' 'Andorra' 'US Virgin Islands' 'Palau'
 'Northern Mariana Islands' 'Samoa' 'Turks and Caicos Islands'
 'FS Micronesia' 'Mayotte' 'Bhutan' 'Kosovo' 'Serbia and Montenegro'
 'Mongolia' 'Serbia' 'Montenegro' 'Kurdistan' 'South Sudan'
 'Saint Barthelemy' 'East Timor' 'Eswatini' 'North Macedonia'
 'São Tome and Principe' 'Sao Tome and Principe']

In [90]:
print(data.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'country', 'neutral', 'homecountries'],
      dtype='object')

In [91]:
data['tags'] = (
    data['date'].astype(str) + " " +
    data['home_team'].astype(str) + " " +
    data['away_team'].astype(str) + " " +
    data['home_score'].astype(str) + " " +
    data['away_score'].astype(str) + " " +
    data['tournament'].astype(str) + " " +
    data['country'].astype(str) + " " +
    data['neutral'].astype(str) + " " +
    data['homecountries'].astype(str)
)

In [92]:
data.head()

,date,home_team,away_team,home_score,away_score,tournament,country,neutral,homecountries,tags
0,1872-11-30,Scotland,England,0,0,Friendly,Scotland,False,Scotland,1872-11-30 Scotland England 0 0 Friendly Scotl...
1,1873-03-08,England,Scotland,4,2,Friendly,England,False,England,1873-03-08 England Scotland 4 2 Friendly Engla...
2,1874-03-07,Scotland,England,2,1,Friendly,Scotland,False,Scotland,1874-03-07 Scotland England 2 1 Friendly Scotl...
3,1875-03-06,England,Scotland,2,2,Friendly,England,False,England,1875-03-06 England Scotland 2 2 Friendly Engla...
4,1876-03-04,Scotland,England,3,0,Friendly,Scotland,False,Scotland,1876-03-04 Scotland England 3 0 Friendly Scotl...

In [93]:
data[['tags']].head()

                                                tags
0  1872-11-30 Scotland England 0 0 Friendly Scotl...
1  1873-03-08 England Scotland 4 2 Friendly Engla...
2  1874-03-07 Scotland England 2 1 Friendly Scotl...
3  1875-03-06 England Scotland 2 2 Friendly Engla...
4  1876-03-04 Scotland England 3 0 Friendly Scotl...

In [94]:
data['homecountries'] = data['homecountries'].str.lower()
data['tags'] = data['tags'].str.lower()
data['home_team'] = data['home_team'].str.lower()
data['away_team'] = data['away_team'].str.lower()
data['tournament'] = data['tournament'].str.lower()
data['country'] = data['country'].str.lower()

In [95]:
data.head()

,date,home_team,away_team,home_score,away_score,tournament,country,neutral,homecountries,tags
0,1872-11-30,scotland,england,0,0,friendly,scotland,False,scotland,1872-11-30 scotland england 0 0 friendly scotl...
1,1873-03-08,england,scotland,4,2,friendly,england,False,england,1873-03-08 england scotland 4 2 friendly engla...
2,1874-03-07,scotland,england,2,1,friendly,scotland,False,scotland,1874-03-07 scotland england 2 1 friendly scotl...
3,1875-03-06,england,scotland,2,2,friendly,england,False,england,1875-03-06 england scotland 2 2 friendly engla...
4,1876-03-04,scotland,england,3,0,friendly,scotland,False,scotland,1876-03-04 scotland england 3 0 friendly scotl...

In [96]:
data['tags_str'] = data['tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else str(x))

In [97]:
data[['home_team', 'away_team', 'tags', 'tags_str']].head()

,home_team,away_team,tags,tags_str
0,scotland,england,1872-11-30 scotland england 0 0 friendly scotl...,1872-11-30 scotland england 0 0 friendly scotl...
1,england,scotland,1873-03-08 england scotland 4 2 friendly engla...,1873-03-08 england scotland 4 2 friendly engla...
2,scotland,england,1874-03-07 scotland england 2 1 friendly scotl...,1874-03-07 scotland england 2 1 friendly scotl...
3,england,scotland,1875-03-06 england scotland 2 2 friendly engla...,1875-03-06 england scotland 2 2 friendly engla...
4,scotland,england,1876-03-04 scotland england 3 0 friendly scotl...,1876-03-04 scotland england 3 0 friendly scotl...

In [98]:
data['neutral']    = data['neutral'].astype(bool)

In [99]:
data.head()

,date,home_team,away_team,home_score,away_score,tournament,country,neutral,homecountries,tags,tags_str
0,1872-11-30,scotland,england,0,0,friendly,scotland,False,scotland,1872-11-30 scotland england 0 0 friendly scotl...,1872-11-30 scotland england 0 0 friendly scotl...
1,1873-03-08,england,scotland,4,2,friendly,england,False,england,1873-03-08 england scotland 4 2 friendly engla...,1873-03-08 england scotland 4 2 friendly engla...
2,1874-03-07,scotland,england,2,1,friendly,scotland,False,scotland,1874-03-07 scotland england 2 1 friendly scotl...,1874-03-07 scotland england 2 1 friendly scotl...
3,1875-03-06,england,scotland,2,2,friendly,england,False,england,1875-03-06 england scotland 2 2 friendly engla...,1875-03-06 england scotland 2 2 friendly engla...
4,1876-03-04,scotland,england,3,0,friendly,scotland,False,scotland,1876-03-04 scotland england 3 0 friendly scotl...,1876-03-04 scotland england 3 0 friendly scotl...

In [100]:
print(data['tags'].head(10))
print(data['tags'].dtype)

0    1872-11-30 scotland england 0 0 friendly scotl...
1    1873-03-08 england scotland 4 2 friendly engla...
2    1874-03-07 scotland england 2 1 friendly scotl...
3    1875-03-06 england scotland 2 2 friendly engla...
4    1876-03-04 scotland england 3 0 friendly scotl...
5    1876-03-25 scotland wales 4 0 friendly scotlan...
6    1877-03-03 england scotland 1 3 friendly engla...
7    1877-03-05 wales scotland 0 2 friendly wales f...
8    1878-03-02 scotland england 7 2 friendly scotl...
9    1878-03-23 scotland wales 9 0 friendly scotlan...
Name: tags, dtype: object
object

In [101]:
data.drop(columns=['tags_str'], inplace=True)
data.head()

,date,home_team,away_team,home_score,away_score,tournament,country,neutral,homecountries,tags
0,1872-11-30,scotland,england,0,0,friendly,scotland,False,scotland,1872-11-30 scotland england 0 0 friendly scotl...
1,1873-03-08,england,scotland,4,2,friendly,england,False,england,1873-03-08 england scotland 4 2 friendly engla...
2,1874-03-07,scotland,england,2,1,friendly,scotland,False,scotland,1874-03-07 scotland england 2 1 friendly scotl...
3,1875-03-06,england,scotland,2,2,friendly,england,False,england,1875-03-06 england scotland 2 2 friendly engla...
4,1876-03-04,scotland,england,3,0,friendly,scotland,False,scotland,1876-03-04 scotland england 3 0 friendly scotl...

# preprocess

In [102]:
def preprocess(text):
    # Step 1 — split sentence into individual words
    tokens = word_tokenize(str(text).lower())
    
    # Step 2 — remove stopwords and non-alphabet words
    filtered = [word for word in tokens if word.isalpha() and word not in stop_words]
    
    # Step 3 — lemmatize (reduce words to root form)
    lemmatised = {lemm.lemmatize(word) for word in filtered}
    
    return lemmatised

In [103]:
from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
lemm = WordNetLemmatizer()

In [104]:
print(preprocess("Will Brazil beat Argentina?"))

{'argentina', 'beat', 'brazil'}

# Intent Classifier

In [105]:
INTENT_TEMPLATES = {
    "predict_winner":    "will win beat predict winner future",
    "head_to_head":      "how many times won beaten total count",
    "home_wins":         "home won hosting ground home record",
    "away_wins":         "away won travel visiting away record",
    "draws":             "draw drew drawn tied tie",
    "last_match":        "last recent latest result score",
    "best_tournament":   "best tournament competition perform wins",
    "worst_performance": "worst loss embarrassing defeat humiliated terrible",
    "win_streak":        "longest streak consecutive wins row kept winning",
    "lose_streak":       "longest losing streak consecutive losses row kept losing",
    "highest_scoring":   "most goals highest scoring thrilling offensive attack",
    "biggest_win":       "biggest dominant victory thrashing hammered crushed margin",
}

In [106]:
def classify_intent(query):
    query_tokens = preprocess(query)
    best_intent, best_score = None, -1
    
    for intent, template in INTENT_TEMPLATES.items():
        template_tokens = preprocess(template)
        overlap = len(query_tokens.intersection(template_tokens))
        if overlap > best_score:
            best_score = overlap
            best_intent = intent
    
    # keyword override — only REPLACES if a keyword is found
    q_lower = query.lower()
    if any(w in q_lower for w in ["will", "who wins", "going to win"]):
        return "predict_winner"
    elif any(w in q_lower for w in ["draw", "drew", "drawn"]):
        return "draws"
    elif "home" in q_lower:
        return "home_wins"
    elif "away" in q_lower:
        return "away_wins"
    elif any(w in q_lower for w in ["last", "recent", "latest"]):
        return "last_match"
    elif any(w in q_lower for w in ["worst", "biggest loss", "embarrass"]):
        return "worst_performance"
    elif any(w in q_lower for w in ["win streak", "winning streak", "consecutive wins"]):
        return "win_streak"
    elif any(w in q_lower for w in ["lose streak", "losing streak", "consecutive loss"]):
        return "lose_streak"
    elif any(w in q_lower for w in ["highest scoring", "most goals"]):
        return "highest_scoring"
    elif any(w in q_lower for w in ["biggest win", "biggest victory", "most dominant"]):
        return "biggest_win"
    # venue based questions also mean prediction
    elif any(w in q_lower for w in [" in ", " at ", "hosted by", "held in"]):
        return "predict_winner"   # "will brazil win IN argentina?" = prediction
    
    return best_intent
    # if NO keyword matched, return whatever the loop found

In [107]:
#testing intent classifier
print(classify_intent("Will Brazil beat Argentina?"))
print(classify_intent("How many times has Germany beaten France?"))
print(classify_intent("How many draws between Spain and Italy?"))
print(classify_intent("What is Brazil's longest winning streak?"))
print(classify_intent("What was England's worst performance?"))

predict_winner
head_to_head
draws
win_streak
worst_performance

# Extracting Country

In [125]:
import re
ALL_TEAMS = set(data['home_team'].unique())|set(data['away_team'].unique())
def extract_countries(query):
    q_lower = query.lower()
    found = []
    for team in sorted(ALL_TEAMS, key=len, reverse=True):
        if re.search(r'\b' + re.escape(team.lower()) + r'\b', q_lower):
            found.append(team)
            if len(found) == 2:
                break
    found.sort(key=lambda t: q_lower.index(t.lower()))

    # ── detect venue ──────────────────────────────────────────
    venue = None
    venue_keywords = [" in ", " at ", " hosted by ", " held in ", " playing in "]
    for keyword in venue_keywords:
        if keyword in q_lower:
            keyword_position = q_lower.index(keyword)
            for team in sorted(ALL_TEAMS, key=len, reverse=True):
                # ✅ start searching ONLY from keyword_position onwards
                team_position = q_lower.find(team.lower(), keyword_position)
                if team_position != -1 and team_position > keyword_position:
                    venue = team
                    break
            break

    return found, venue

In [126]:
# Test
print(extract_countries("Will Brazil win against Argentina in Argentina?"))
print(extract_countries("Will France beat England in England?"))
print(extract_countries("Will Brazil beat Argentina?"))

(['brazil', 'argentina'], 'argentina')
(['france', 'england'], 'england')
(['brazil', 'argentina'], None)

# Stat Helper

In [53]:
def get_h2h(t1, t2):
    return data[
        ((data['home_team'] == t1) & (data['away_team'] == t2))|
        ((data['home_team'] == t2) & (data['away_team' == t1]))
        ]

def team_won(row, team):
    if row['home_team'] == team:
        return row['home_score'] > row['away_score']
    return row['home_score'] < row['away_score']

In [ ]:
#get_h2h It returns a filtered dataframe, just the rows where these two teams played each other
#team_won tells us if the home team won or not, if home score is more than away score it returns true, if away score is more it returns false

# All Handlers

In [ ]:
def handle_predict(t1, t2, venue=None):
    h2h = get_h2h(t1, t2)
    if h2h.empty():
        return f"No historical data found between {t1} and {t2}."
    total = len(h2h)
    w1 = sum(team_won(r, t1) for _, r in h2h.iterrows())
    w2 = sum(team_won(r, t2) for _, r in h2h.iterrows())
    draws = total - w1 - w2
    f1_t1 = w1 / total
    f1_t2 = w2 / total # ratio of wins by total matches that happen

    #for recent 5 matches
    recent = h2h.sort_values('date').tail(5)
    rw1 = sum(team_won(r, t1) for _, r in recent.iterrows())
    rw2 = sum(team_won(r, t2) for _, r in recent.iterrows())
    f2_t1 = rw1 / len(recent)
    f2_t2 = rw2 / len(recent) # ratio of recent wins by recent matches


    #home adv based on venue
    if venue is None:
        venue_label = "Venue Unknown"
        home_matches = data[(data['home_team'] == t1) & (~data['neutral'])] # "give me rows where t1 is home team AND match is NOT neutral
        f3_t1 = home_matches['home_score'] > home_matches['away_score'].sum()/len(home_matches) if len(home_matches) > 0 else 0.5
        away_matches = data[(data['away_team'] == t2) & (~data['neutral'])] # away_matches = all matches where Argentina travelled to another country
        f3_t2 = away_matches['away_score'] > away_matches['home_score'].sum()/len(away_matches) if len(away_matches) > 0 else 0.5